### ISSUE TITLE
Jetson Ballot examples reviewed and moved

### ISSUE THREAD

**Issue by awoflaherty** [TrustTheVote-Project/NIST-1500-100-103-examples#38]
1. Does it make sense to move /test_cases/ as a folder under examples?

2. Are these example files up to date with NIST v2?

3. Should these be duplicated and placed in the Rosie repo?
https://github.com/trustthevote/MVP-App-TestHarness/tree/main/src/assets/files

**Comment by cwulfman** [comment]
My thoughts on your questions; obviously you and @trustthevote should decide what is best for you.

The purpose of this repository has evolved; it started out a a resource for developers wanting to understand EDFs and CVRs.  And as I understood it, the MVP Test Harness was no longer being used; now I see that is not the case. I'd like to propose two options:

1. Transfer the test cases to the Rosie repository and drop this repository. Or move just the JSON files to MVP Test Harness, since those are the only files that will actually be used.
2.  Create a new repository that contains testing, bench-marking, and evaluation assets for all the TTV projects and move the test cases there.

In either case, I suggest we eliminate this repository.

**Comment by cwulfman** [comment]
This issue is stale; I am closing it.
